# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

management:
    context-path: /management
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true
spring:
    application:
        name: pasaas
        url: http://analytics.pervazive.com/pasaas
    profiles:
        # The commented value for `active` can be replaced with valid Spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: #spring.profiles.active#
    jackson:
        serialization.write_dates_as_timestamps: false
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML
    
    http:
      multipart:
        enabled: true
        max-file-size: 128MB
        max-request-size: 128MB
      
      
    social:
        # see https://developers.google.com/+/web/signin/server-side-flow#step_1_create_a_client_id_and_client_secret
        google:
            clientId: 533395353669-apdpr17k9dcmgmm2vi8r8qevirot22pi.apps.googleusercontent.com
            clientSecret: -WJTvVQCOeuKc7oZUkUk0udt

        
        # see https://developers.facebook.com/docs/facebook-login/v2.2
        facebook:
            clientId: 400876320274560
            clientSecret: e8dc121031bb8c0fbcc5fa9b7b23d3e0

        # see https://apps.twitter.com/app/
        twitter:
            clientId: hRkj3wYYrcryHdpnijI1pGHfg
            clientSecret: WkU5e4u0vTyA5iQa8ENIEwrRh8hhGU2avkBNS5X8S5M0KW46ae

        # jhipster-needle-add-social-configuration

security:
    basic:
        enabled: false

server:
    session:
        cookie:
            http-only: true
            


# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    cors: #By default CORS are not enabled. Uncomment to enable.
        allowed-origins: "http://pervazive.gurusoftwares.in"
        allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        allowed-headers: "*"
        exposed-headers:
        allow-credentials: true
        max-age: 1800
    mail:
        from: pasaas@localhost
    swagger:
        title: pasaas API
        description: pasaas API documentation
        version: 0.0.1
        termsOfServiceUrl:
        contactName:
        contactUrl:
        contactEmail:
        license:
        licenseUrl:
    social:
        redirectAfterSignIn: "/#/home"
    ribbon:
        # comma separated list of profiles to show a ribbon on the GUI
        displayOnActiveProfiles: dev
